### ISSUE TITLE
Menu Scrolling

### ISSUE THREAD

**Issue by rauhul** [HackIllinois/iOS#124]
Add a `MENU_MAX_HEIGHT` constant to HIMenuController. If the menu contents exceeds this height, the contents should be scrollable.

https://github.com/HackIllinois/iOS/blob/47d4211fda0512fe820f449f5ac7fed251cf4198/HackIllinois/Controllers/FlowControllers/HIMenuController.swift#L23-L25

**Comment by lasyaneti** [comment]
Outdated issue.
