### ISSUE TITLE
Show upcoming event on home screen

### ISSUE THREAD

**Issue by rauhul** [HackIllinois/iOS#125]
Extend start to be 15 minutes before now() such that events that begin shortly are included in this view

https://github.com/HackIllinois/iOS/blob/47d4211fda0512fe820f449f5ac7fed251cf4198/HackIllinois/Controllers/ViewControllers/HIEventViewControllers/HIHomeViewController.swift#L29

**Comment by lasyaneti** [comment]
Outdated issue.
