### ISSUE TITLE
Validate accounts retrieved from keychain

### ISSUE THREAD

**Issue by rauhul** [HackIllinois/iOS#126]
Theres a chance that a recovered account will have a token that is revoked, we should probably validate this token. Applies to both GitHub oauth and user-pass login.

https://github.com/HackIllinois/iOS/blob/df83a7d9c8da00d99e995cd40c1047cf98fcf398/HackIllinois/Controllers/FlowControllers/HILoginFlowController.swift#L175

**Comment by lasyaneti** [comment]
Outdated issue.
