### ISSUE TITLE
Events not displaying on ScheduleViewController

### ISSUE THREAD

**Issue by darthbatman** [HackIllinois/iOS#156]
ScheduleViewController inconsistently displayed 0 to 1 events, may be issue with fetchrequest or NSPredicates.

**Comment by PatrickKan** [comment]
Also not displaying in HomeViewController, due to events being fetched or filtered incorrectly

**Comment by darthbatman** [comment]
fixed on dev-oauth

**Comment by darthbatman** [comment]
still needs to be merged

**Comment by rauhul** [comment]
fixed by #162
