### ISSUE TITLE
Differentiate errors in scanning for events + check-in

### ISSUE THREAD

**Issue by PradyumnaShome** [HackIllinois/iOS#225]
Specifically, tell the staff member who is scanning whether the user has already scanned for the current event(double scan) OR if the user has not checked in to HackIllinois. The API supports this, via the message property, but this information needs to be propagated client-side.

It is easier to know what to do based on the attendee's scenario given this information.

**Comment by redsn0w422** [comment]
The iOS app currently displays exactly what comes back from the API.

**Comment by lasyaneti** [comment]
Outdated issue.
