### ISSUE TITLE
Hit refresh endpoint to refresh JWT or log out user when JWT expires

### ISSUE THREAD

**Issue by PatrickKan** [HackIllinois/iOS#350]
For refresh endpoint: GET /auth/token/refresh/
https://docs.hackillinois.org/reference/services/Authorization/

OR (combination of the both below)

Log the user out when their token expires (403 forbidden error when trying to make an API call to favorites)
Ideas when to log out user (make sure they are not a guest):
* Make an API call to refresh endpoint every time they open the app, and if it's unauthorized then log them out gracefully with an alert message, but this could be a lot of API calls
* Any time a 403 is detected, log them out with an alert message if they are not a Guest

**Comment by lasyaneti** [comment]
Outdated issue.
