### ISSUE TITLE
Leaderboard View

### ISSUE THREAD

**Issue by ashayp22** [HackIllinois/iOS#383]
**Goal**
The fifth tab in the 2022 app will be a Leaderboard view. We need to fetch the required data from the API and display this in a rudimentary table view for now.

**Steps**
1. ~~Replace HIGroupViewController with a new Leaderboard view controller.~~
2. ~~Add a table view.~~
3. ~~Populate table view with random data.~~
4. Call [`GET /profile/leaderboard/?limit=`](https://docs.hackillinois.org/reference/services/Profile/#get-profileleaderboardlimit) to get the actual leaderboard data. For this, we will need to create a DataSource for the leaderboard data, add a Leaderboard Model, and add a Leaderboard service. For right now, the limit can be 10 people. 

***For now, no need to worry about tiers.***

**Additional Comments**
No need to worry about the design for this view.

**Comment by carters101** [comment]
Addressed issues (minus design) and sent for PR

**Comment by ashayp22** [comment]
Been merged.
