### ISSUE TITLE
QR Scanner

### ISSUE THREAD

**Issue by ashayp22** [HackIllinois/iOS#384]
**Goal:**
Staff and attendees will need to scan QR codes during HackIllinois. This feature will be accessed by clicking the middle button in the navbar. Then, a QR scanner should pop up. 

**Steps:**
1. ~~Replace HICodePopupViewController with a new view controller for scanning QR codes. Reference the code in HIBaseScannerViewController, HIEventScannerViewController, and HICheckInScannerViewController for this.~~
2. ~~Save the data from the QR code locally.~~
3. Create a dropdown picker for selecting the event that you are scanning for. For now, make the fields the name of **every** event. The code for fetching the events is in HIScheduleViewController. 
4. Filter the events. Staff will be scanning for check-in and meals. Attendees will scan all other events. Each event has an event type. We can use this event type to do the filtering. 

***Note: attendees won't need a dropdown picker since the QR code that they scan will identify the event that they are attending.***

Endpoints: 

`POST /checkin/` - Staff checking in attendees at the beginning. Refer to `CheckInService` in `HIAPI` for this request.
`POST /event/track/` - Staff scanning for meals. Needs `eventID` and `userID`
`POST /event/checkin/` - Attendees scanning for workshops, QNA, etc. Needs `eventCode` (acquired from scanning QR code).

(There already is code for calling these endpoints)

**Additional Comments:**
No need to worry about the design for this pop-up.

**Comment by ifisq** [comment]
Branch created with first two steps completed - https://github.com/HackIllinois/iOS/tree/aryan/qr-scanner

**Comment by ashayp22** [comment]
Been merged.
