### ISSUE TITLE
Update Home View with Hack 2022 Designs

### ISSUE THREAD

**Issue by ashayp22** [HackIllinois/iOS#398]
**Goal**

- Update the background of the Home View with the Cloud Gradient background on Figma.
- Update the Countdown title to "What's Cooking?" and add the Chicken background to the Timer.
- Update the Event Cards (HIEventCell) with the Hack 2022 Design.
- Update the header titles.

**Comment by hsahn0323** [comment]
(Unconfirmed) Changes from current Figma event cell:

- Sponsor
- Replace "In-Person Only" with event type
