### ISSUE TITLE
Authentication Failed during Attendee Login

### ISSUE THREAD

**Issue by vincentbanguyen** [HackIllinois/iOS#479]
**Describe the bug**

**To Reproduce**
1. Go to login screen
2. Click login as attendee

**Expected behavior**
Get prompted the github login page

**Screenshots**
![image](https://user-images.githubusercontent.com/72878425/210905250-58c75b43-4041-4f7b-b503-312eea5dd983.png)

**Environment (please complete the following information):**
 - Device: Simulator: IPhone 14

**Comment by louisunlimited** [comment]
possibly resolved by #480

**Comment by lasyaneti** [comment]
Test account has been added back. Auth works on my end, should be fixed!
