### ISSUE TITLE
Staff QR Scanner, Profile bugs

### ISSUE THREAD

**Issue by lasyaneti** [HackIllinois/iOS#515]
## Staff QR Scanner
- [ ] Display dietary restriction (exactly as it is in the API) on staff's end 

## Profile Dietary Restriction 
- [ ] Need placeholder for "None" (see screenshot) --> I believe API is sending an empty array now
![IMG_7626](https://user-images.githubusercontent.com/44485522/218226848-d4a6e117-4b8c-45e3-b94d-818f35686db0.png)

- [ ] Display anything not from the standard options as "custom" on profile, but display full form on staff's end when scanned

**Comment by vincentbanguyen** [comment]
https://github.com/HackIllinois/iOS/pull/516 might need some more testing to make sure it works.

**Comment by lasyaneti** [comment]
#519
