### ISSUE TITLE
Match API schema update to events followed

### ISSUE THREAD

**Issue by anushkasankaran** [HackIllinois/iOS#594]
Change in API:
- ```GET /user/following/``` properly returns followed events as ```{ userId: "123", following: ["event1",...] }``` instead of ```{ userId: "123", events: ["event1",...] }```

Events are returned under the ```following``` field instead of the previous ```events``` field. Update the iOS model to match the new name for the field.

[Link to API docs](https://adonix.hackillinois.org/docs/#/)

**Comment by yashjagtap23** [comment]
<img width="337" alt="Screenshot 2024-11-06 at 8 40 29 PM" src="https://github.com/user-attachments/assets/0a94d77f-bfe9-4e79-9d96-2060b7342c9f">
I believe this has already been implemented.
